apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # tên của deployment
  name: go-example
spec:
  # số POD tạo ra
  replicas: 1
  # thiết lập các POD do deploy quản lý, là POD có nhãn  "app=deployapp"
  selector:
    matchLabels:
      app: go-example

  # Định nghĩa mẫu POD, khi cần Deploy sử dụng mẫu này để tạo Pod
  template:
    metadata:
      name: podapp-go
      labels:
        app: go-example
    spec:
      containers:
      - name: node
        #image: ichte/swarmtest:node
        image: giaple/demogo:latest
        ports:
          - containerPort: 81
