apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go
  labels:
    app: goserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: go
        image: image: giaple/demogo:latest
        ports:
        - containerPort: 81
