apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  selector:
    app: goApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 60081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
  labels:
    app: go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go
        image: giaple/gotest:latest
        ports:
        - containerPort: 8081
---          
#namespace
apiVersion: v1
kind: Namespace
metadata:
  name: giaplv-app-go 
---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: go-demo
#spec:
#  containers:
#  - name: go-demo
#    image: debian
#    terminationMessagePath: "/tmp/my-log"
